'use strict';
let h1 = document.querySelector('h1');
console.log('h1:', h1);
console.dir(h1);
let explanation = document.querySelector('#explanation');
console.log('#explanatation: ', explanation);
console.dir(explanation);
let hint = document.querySelector('.hint');
console.log('.hint: ', hint);
console.dir(hint);
let pElements = document.querySelectorAll('p');
console.log('pElements: ', pElements);
let exampleLink = document.querySelectorAll('.example-link');
console.log(exampleLink);
