'use strict';
const fullName = 'Cody Epstein';
const isCool = true;
const totalPets = 1;
console.log('Full Name: ' + fullName);
console.log('Type of fullName: ' + typeof fullName);
console.log('isCool: ' + isCool);
console.log('Type of isCool: ' + typeof isCool);
console.log('Number of pets: ' + totalPets);
console.log('Type of totalPets: ' + typeof totalPets);
const empty = null;
console.log('Empty: ' + empty);
console.log('Type of empty: ' + typeof empty);
let nothing;
console.log('Nothing: ' + nothing);
console.log('Type of nothing: ' + typeof nothing);
